Simplify request wrapper
auth0/node-jwks-rsa pull request #218
Opened 2021-02-11 21:58 UTC by davidpatrick

## Description
The goal of this PR is to expand the support for users of this library to fully customize the underlying request, while simplifying the default request options.

### Adds
- `options.fetcher` - this is a promise returning function that fetches the jwks data.  We want to make sure that users can fully customize how data is fetched, this option will allow for a user to replace the underlying request logic and supply their own data fetching logic.
- `options.requestAgent` - previously we gated the options that could be passed into a requestAgent, which required we have some type of frankenstein solution for supporting proxies.  This will allow the user supply their own agent in the request and thus allowing them to support the proxy at this level.
### Removes
- `options.requestAgentOptions` - now with `requestAgent` this will no longer be needed
- `options.proxy` - now with `requestAgent` a user can control their proxy flow, and with the `fetcher` option a user can completely control the request flow
- `axios` - we have had a lot of issues pop up after moving from the EOL `request` library to `axios`.  With the `fetcher` option, a user can now use their own request library, and this PR introduces using the node internals to make the requests.

2021-02-17 21:13 UTC, panva commented on src/wrappers/request.js
> +        'Content-Type': 'application/json',
the request doesn't have any specific content type, as it's a get and bears no body. You might've thought to have an Accept header but even then the application/json is speculative as per the JWK spec its meant to be `application/jwk-set+json`. Best to leave both content-type and accept headers out completely.

2021-02-23 16:11 UTC, adamjmcgrath requested changes
lgtm - couple of suggestions

2021-02-23 16:11 UTC, adamjmcgrath commented on package.json
>      "axios": "^0.21.1",
You can remove `axios`

2021-02-23 16:11 UTC, adamjmcgrath commented on README.md
> -  proxy: '[protocol]://[username]:[pass]@[address]:[port]', // Optional
Add `requestAgent`

2021-02-23 16:11 UTC, adamjmcgrath commented on index.d.ts
> +    fetcher?(jwksUri: string): Promise<unknown>;
```
import { Agent as HttpAgent } from 'http';
import { Agent as HttpsAgent } from 'https';

...
requestAgent?: HttpAgent | HttpsAgent;
fetcher?(jwksUri: string): Promise<{ keys: SigningKey[] }>;
```

2021-02-23 19:46 UTC, davidpatrick commented on README.md
> -  proxy: '[protocol]://[username]:[pass]@[address]:[port]', // Optional
I left this one out because I thought it might look a little strange to have the whole line commented out for `requestAgent`.

2021-02-23 19:50 UTC, davidpatrick commented on README.md
> -  proxy: '[protocol]://[username]:[pass]@[address]:[port]', // Optional
A user would still be able to see the `requestAgent` use-cases further down in the Readme, and also in the type definitions

2021-02-24 16:12 UTC, adamjmcgrath approved these changes

2021-02-24 16:13 UTC, panva approved these changes

2021-02-24 20:56 UTC, merged